export const actions = {
  setTitleHtml: 'SET_TITLE_HTML',
  setContentHtml: 'SET_CONTENT_HTML',
  getTitleHtml: 'GET_TITLE_HTML',
  getContentHtml: 'GET_CONTENT_HTML',
  blurTitleEditor: 'BLUR_TITLE_EDITOR',
  blurContentEditor: 'BLUR_CONTENT_EDITOR',
  setBold: 'SET_BOLD',
  setItalic: 'SET_ITALIC',
  setUnderline: 'SET_UNDERLINE',
  heading1: 'HEADING1',
  heading2: 'HEADING2',
  heading3: 'HEADING3',
  heading4: 'HEADING4',
  heading5: 'HEADING5',
  heading6: 'HEADING6',
  setParagraph: 'SET_PARAGRAPH',
  removeFormat: 'REMOVE_FORMAT',
  alignLeft: 'ALIGN_LEFT',
  alignCenter: 'ALIGN_CENTER',
  alignRight: 'ALIGN_RIGHT',
  alignFull: 'ALIGN_FULL',
  insertBulletsList: 'INST_BULLETS',
  insertOrderedList: 'INST_ORDERED',
  setSubscript: 'SET_SUB',
  setSuperscript: 'SET_SUPER',
  setStrikethrough: 'SET_STRIKETHRU',
  setHR: 'SET_HR',
  setIndent: 'SET_INDENT',
  setOutdent: 'SET_OUTDENT',
  setTitlePlaceholder: 'SET_TITLE_PLACEHOLDER',
  setContentPlaceholder: 'SET_TITLE_PLACEHOLDER',
  setTitleFocusHandler: 'SET_TITLE_FOCUS_HANDLER',
  setContentFocusHandler: 'SET_CONTENT_FOCUS_HANDLER'
};

export const messages = {
  TITLE_HTML_RESPONSE: 'TITLE_HTML_RESPONSE',
  CONTENT_HTML_RESPONSE: 'CONTENT_HTML_RESPONSE',
  ZSS_INITIALIZED: 'ZSS_INITIALIZED',
  SCROLL: 'SCROLL',
  LOG: 'LOG',
  TITLE_FOCUSED: 'TITLE_FOCUSED',
  CONTENT_FOCUSED: 'CONTENT_FOCUSED'
}
