export const actions = {
  setTitleHtml: 'SET_TITLE_HTML',
  setContentHtml: 'SET_CONTENT_HTML',
  getTitleHtml: 'GET_TITLE_HTML',
  getContentHtml: 'GET_CONTENT_HTML',
  blurTitleEditor: 'BLUR_TITLE_EDITOR',
  blurContentEditor: 'BLUR_CONTENT_EDITOR',

  setBold: 'bold',
  setItalic: 'italic',
  setUnderline: 'underline',
  heading1: 'h1',
  heading2: 'h2',
  heading3: 'h3',
  heading4: 'h4',
  heading5: 'h5',
  heading6: 'h6',
  setParagraph: 'SET_PARAGRAPH',
  removeFormat: 'REMOVE_FORMAT',
  alignLeft: 'justifyLeft',
  alignCenter: 'justifyCenter',
  alignRight: 'justifyRight',
  alignFull: 'justifyFull',
  insertBulletsList: 'unorderedList',
  insertOrderedList: 'orderedList',
  insertLink: 'INST_LINK',
  insertImage: 'INST_IMAGE',
  setSubscript: 'subscript',
  setSuperscript: 'superscript',
  setStrikethrough: 'strikeThrough',
  setHR: 'horizontalRule',
  setIndent: 'indent',
  setOutdent: 'outdent',
  setTitlePlaceholder: 'SET_TITLE_PLACEHOLDER',
  setContentPlaceholder: 'SET_TITLE_PLACEHOLDER',
  setTitleFocusHandler: 'SET_TITLE_FOCUS_HANDLER',
  setContentFocusHandler: 'SET_CONTENT_FOCUS_HANDLER'
};


export const messages = {
  TITLE_HTML_RESPONSE: 'TITLE_HTML_RESPONSE',
  CONTENT_HTML_RESPONSE: 'CONTENT_HTML_RESPONSE',
  ZSS_INITIALIZED: 'ZSS_INITIALIZED',
  SCROLL: 'SCROLL',
  LOG: 'LOG',
  TITLE_FOCUSED: 'TITLE_FOCUSED',
  CONTENT_FOCUSED: 'CONTENT_FOCUSED',
  SELECTION_CHANGE: 'SELECTION_CHANGE'
}
